#!/usr/bin/env node
// Writes the seed migration from the committed snapshot, so what the app
// shows and what the database holds come from one file and can't drift.
//
//   pnpm drizzle-kit generate --custom --name=seed_catalogue
//   node scripts/seed-sql.ts drizzle/<that file>.sql
//
// A later snapshot gets a new custom migration, never an edit to an applied
// one: the Fly volume has already run it.
import { readFileSync, writeFileSync } from "node:fs";

const out = process.argv[2];
if (!out?.endsWith(".sql")) {
  console.error("usage: node scripts/seed-sql.ts drizzle/<migration>.sql");
  process.exit(1);
}

type CatalogueCourse = {
  code: string;
  title: string;
  units: number;
  mode: string;
  description: string;
  requisiteText: string;
  convener: string | null;
  classStart: string | null;
  classEnd: string | null;
  enrolBy: string | null;
  census: string | null;
  sourceUrl: string;
};
type TimetableActivity = {
  activity: string;
  group: string;
  kind: string;
  day: string;
  start: string;
  end: string;
  location: string;
};

const catalogue = JSON.parse(readFileSync("src/data/catalogue.json", "utf8")) as {
  courses: CatalogueCourse[];
};
const timetable = JSON.parse(readFileSync("src/data/timetable.json", "utf8")) as {
  activities: Record<string, TimetableActivity[]>;
};

// Fictional students, each showing a different side of eligibility.
const STUDENTS = [
  {
    // The default: no cookie means Alex. Mid-degree, can take most courses.
    id: "alex",
    name: "Alex Morgan",
    program: "MCOMP",
    completed: ["COMP6710", "COMP6260", "COMP6250"],
    plan: [],
  },
  {
    // Just started the advanced master's: program rules decide most things.
    id: "priya",
    name: "Priya Raman",
    program: "VCOMP",
    completed: [],
    plan: [],
  },
  {
    // Final semester, already carrying 18 units.
    id: "jordan",
    name: "Jordan Ellis",
    program: "MCOMP",
    completed: ["COMP6710", "COMP6260", "COMP6442", "COMP6120", "COMP8280", "COMP6240", "COMP6670", "COMP6390"],
    plan: ["COMP6331", "COMP8410", "COMP8600"],
  },
];

const q = (v: string | number | null) =>
  v === null ? "NULL" : typeof v === "number" ? String(v) : `'${v.replaceAll("'", "''")}'`;
const row = (values: (string | number | null)[]) => `(${values.map(q).join(", ")})`;

const statements = [
  `INSERT INTO courses (code, title, units, mode, description, requisite_text, convener, class_start, class_end, enrol_by, census, source_url) VALUES\n${catalogue.courses
    .map((c) =>
      row([
        c.code,
        c.title,
        c.units,
        c.mode,
        c.description,
        c.requisiteText,
        c.convener,
        c.classStart,
        c.classEnd,
        c.enrolBy,
        c.census,
        c.sourceUrl,
      ]),
    )
    .join(",\n")};`,
  `INSERT INTO activities (course_code, activity, "group", kind, day, start, "end", location) VALUES\n${Object.entries(
    timetable.activities,
  )
    .flatMap(([code, acts]) =>
      acts.map((a) => row([code, a.activity, a.group, a.kind, a.day, a.start, a.end, a.location])),
    )
    .join(",\n")};`,
  `INSERT INTO students (id, name, program) VALUES\n${STUDENTS.map((s) => row([s.id, s.name, s.program])).join(",\n")};`,
  `INSERT INTO completed_courses (student_id, course_code) VALUES\n${STUDENTS.flatMap((s) =>
    s.completed.map((c) => row([s.id, c])),
  ).join(",\n")};`,
  `INSERT INTO enrolments (student_id, course_code) VALUES\n${STUDENTS.flatMap((s) =>
    s.plan.map((c) => row([s.id, c])),
  ).join(",\n")};`,
];

// better-sqlite3 runs one statement at a time; drizzle splits on this marker.
writeFileSync(
  out,
  `-- Generated by scripts/seed-sql.ts from src/data/. Do not edit by hand.\n${statements.join("\n--> statement-breakpoint\n")}\n`,
);
console.log(`wrote ${out}`);
